quarkus:
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:default
    foo:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:foo
    bar:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:bar
